blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.blog_index, name="blog_index"),
  path('createnew/', views.add_new_activity,name="create_new_activity")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views as accountViews
from blog import views as blogViews
from suggest import views as suggestViews

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
		path('', include('blog.urls')),
    path('sop/', include('sop.urls')),
    path('register/', accountViews.register, name="register"),
    path('', include("django.contrib.auth.urls")),
    path('portal/', blogViews.portal, name="portal"),
    path('random/', suggestViews.suggest, name="suggest")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

sop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('about/', views.about, name="about"),
		path('', views.sop, name="sop"),
]

blog/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
  def __str__(self):
    return self.name
  name = models.CharField(max_length=255)


class State(models.Model):
  def __str__(self):
    return self.name
  name = models.CharField(max_length=255)


class Activity(models.Model):
  def __str__(self):
    return self.shopname

  username = models.CharField(max_length=255)
  shopname = models.CharField(max_length=255)
  descriptions = models.CharField(max_length=4000)
  hiring = models.CharField(max_length=20, null=True, blank=True)
  category = models.ManyToManyField('Category', related_name='activity')
  # category = models.CharField(max_length=255, null=True)
  
  state = models.ManyToManyField('State', related_name='activity')
  image = models.ImageField(upload_to='picture/', null=True, blank=True)

  created_on = models.DateTimeField(auto_now_add=True)
  last_modified = models.DateTimeField(auto_now=True)

blog/forms.py
from django import forms
from .models import Category

class ActivityForm(forms.Form):
    shopname = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Activity Name",
        })
    )
    
    descriptions = forms.CharField(
        max_length=4000,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Descriptions"
        })
    )
    
    states = (
        ('1', 'Johor'),
        ('2', 'Kedah'),
        ('3', 'Kelantan'),
        ('4', 'Malacca'),
        ('5','Negeri Sembilan'),
        ('6', 'Pahang'),
        ('7', 'Penang'), 
        ('8', 'Perak'),
        ('9', 'Perlis'),
        ('10', 'Sabah'),
        ('11', 'Sarawak'),
        ('12', 'Selangor'),
        ('13', 'Terengganu'),
        ('14', 'Kuala Lumpur'),
        ('15', 'Labuan'),
        ('16', 'Putrajaya'),
    )

    state = forms.ChoiceField(choices=states)

    # category = forms.CharField(
    #     max_length=255,
    #     widget=forms.TextInput(attrs={
    #         "class": "form-control",
    #         "placeholder": "Category"
    #     })
    # )

    category = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    image = forms.ImageField()

class search(forms.Form):
  keyword = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
            "class": "form-control search-text",
            "placeholder": "Search...",
            "style": "color: black;",
        }))

sop/forms.py
from django import forms

class Landing_form(forms.Form):

	states = (
		('JOHOR', 'Johor'),
		('KEDAH', 'Kedah'),
		('KELANTAN', 'Kelantan'),
		('MALACCA', 'Malacca'),
		('NEGERI SEMBILAN','Negeri Sembilan'),
		('PAHANG', 'Pahang'),
		('PENANG', 'Penang'),
		('PERAK', 'Perak'),
		('PERLIS', 'Perlis'),
		('SABAH', 'Sabah'),
		('SARAWAK', 'Sarawak'),
		('SELANGOR', 'Selangor'),
		('TERENGGANU', 'Terengganu'),
		('KUALA LUMPUR', 'Kuala Lumpur'),
		('LABUAN', 'Labuan'),
		('PUTRAJAYA', 'Putrajaya'),
	)
	state = forms.ChoiceField(choices=states)
	fully_vaccinated = forms.BooleanField(required = False)

blog/views.py
from django.shortcuts import render
from itertools import chain
# from django.http import HttpResponse

# from django.contrib.auth.decorators import login_required

# Create your views here.
from blog.models import Activity, State
from .forms import ActivityForm, search
from django.contrib import messages
from sop.forms import Landing_form


def blog_index(request):
  if request.method == "POST":
    form = search(request.POST)
    searched = request.POST["keyword"]
    fetch1 = Activity.objects.filter(shopname__contains=searched).order_by('-created_on')
    fetch2 = Activity.objects.filter(username__contains=searched).order_by('-created_on')
    fetch3 = Activity.objects.filter(descriptions__contains=searched).order_by('-created_on')
    fetch4 = {}
    for i in Activity.objects.all():
      for j in i.category.all():
        if j == searched:
          fetch5 = list(j)
          fetch4 = list(chain(fetch4, fetch5))
    fetch = list(chain(fetch1, fetch2, fetch3, fetch4))
    context = {
      "form": form,
      "posts": fetch,
    }
  else:
    form = search()
    posts = Activity.objects.all().order_by('-created_on')
    context = {
        "form": form,
        "posts": posts,
    }
  return render(request, "blog_index.html", context)

"""
    Display all activities
    posts = Activity.objects.all().order_by('-created_on')
    context = {
        "posts": posts,
    }
    return render(request, "blog_index.html", context)
"""

# @login_required(login_url='login/')
def add_new_activity(request):
  form = ActivityForm()
  if request.method == 'POST':
    # print(request.POST)
    form = ActivityForm(request.POST,request.FILES)
    if form.is_valid():
      state=form.cleaned_data["state"]
      img = form.cleaned_data["image"]
      username=request.user
      shopname=form.cleaned_data["shopname"]
      descriptions=form.cleaned_data["descriptions"]
      category=form.cleaned_data["category"]
      instance = Activity.objects.create(
        username=username,
        shopname=shopname,
        descriptions=descriptions,
        # category=category,
        image=img,
      )
      instance.state.set(state)
      instance.category.set(category)

      messages.success(request, 'Form submission successful')

  context = {
    "form": form,
    "user": request.user,
  }
  return render(request, "new_activity.html", context)

def portal(request):
  return render(request, "portal.html", {})

# def portal(request):
#   form = Landing_form()
#   return render(request, "test.html", {"form": form})


# obj = State.set(
# 	username=request.user,
# 	shopname=form.cleaned_data["shopname"],
# 	descriptions=form.cleaned_data["descriptions"],
# 	state=form.cleaned_data["state"],
# 	category=form.cleaned_data["category"],
# 	img = img,
# )
# obj.save()
			

blog/templates/about.html
{% extends "base.html" %}

{% block content %}
{% load static %}

  <div class="container">
      <h1 style='color: black'>About Us</h1>
      <p>At such struggling times, we, the Meme Team is here to guide you to your solutions. From complicated, hard-to-understand SOPs to killing time with learning resources, we've simplified and packaged it into a single, neat website, just for you!</p>
    
    <br>
    <button class="button" style="vertical-align:middle" onclick="location.href='https://covid-19.moh.gov.my/hotline'">
      <span>Hotlines</span>
    </button>

<br>
      
  <div class="container" style='color: black;'>
    <h2>Contact Us</h2>
    <div class="contact">
      <a href="https://www.instagram.com/hsinorshin/" target="_blank"><button class="button" style="vertical-align:middle">
        <span ><img src="{% static 'assets/images/InstagramLogo.png' %}" alt="insta logo"> @xxx</span>
      </a>
 
      <a href="mailto:bangtan0526@gmail.com" target="_blank"><button class="button" style="vertical-align:middle">
        <span><img src="{% static 'assets/images/Emaillogo.png' %}" alt="email logo"> xxx@gmail.com</span>
      </a>

      <button class="button" style="vertical-align:middle">
        <span><img src="{% static 'assets/images/PhoneLogo.png' %}" alt="phone logo"> +6012-3456789</span>
      
      </div>     
  </div>
  </div>

{% endblock %}

blog/templates/blog_index.html
{% extends "base.html" %}

{% block content %}
{% load static %}
  

    <!-- <div class="search">
    <input name='search' type='text' placeholder="Search &#8711;">
    </div> -->
    <div class="search">
      <form method="POST" class="search_form">
      {% csrf_token %}
      {{ form }}
      <input class='submit-btn'type="submit" value='Search' />
      </form>
    </div>
    {% for post in posts %}
    <div class="feed">
      <div class="feed-left">
      <div class="feed-username">{{post.username}}</div>
      <!-- <img class="feed-img" src="{% static 'assets/images/VeganFood.jpg' %}"  alt='veganfood'> -->
      <img class="feed-img" src="{{ post.image.url }}"  alt='veganfood'>
      </div>
      <div class="feed-right" >
      <div id='feed-right'>{{post.shopname}}</div>
      <div id='feed-right'>{{post.descriptions}}</div>
      <div id='feed-right'>{% for category in post.category.all %}
        <div id='feed-right'>{{category}}</div>{% endfor %}</div>
      <div id='feed-right'>{% for state in post.state.all %}
        <div id='feed-right'>{{state}}</div>{% endfor %}</div>
      </div>
    </div>
    {% endfor %}
      <!-- <div class="feed-tag">
        <span>{{tag1}}</span>
        <span>{{tag2}}</span>
        <span>{{tag3}}</span>
      </div> -->
 
{% endblock %}

blog/templates/new_activity.html
{% extends "base.html" %}


{% block content %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if user.is_authenticated %}
    {{form.as_p}}
    <button type="submit" name="click" value="click">Submit</button>
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li
        {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
      {% endfor %}
    </ul>
  {% endif %}
    {% else %}
    <p>Only members can submit activities, login <a href="/login">here</a></p>
    {% endif %}
  </form>

<!-- {% if user.is_authenticated %}

{% else %}
<p>Please login first, click <a href="/login">here</a></p>
{% endif %} -->

{% endblock %}

blog/templates/portal.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>repl.it</title>
    <link href="style.css" rel="stylesheet" type="text/css" />
    
      </style>
  </head>
  <body>

    <div class="container submit">
      <a href={% url 'create_new_activity' %}>
      <h1 style="color: black" class="submit-header">Submit an activity!</h1>
      </a>
      <p>
        Do you own a business, or run an activity that you'd like others to know about?
       <br>
       <br>
        Register to submit a post, & it will show up on the feed for those who can access it according to their location & vaccination status.

      <br>
       <br>

        You can also submit on behalf of someone else, just make sure to include their contact information!
      

      </p>
      
      <br>

      <h3>Submissions include:</h3>
      <ul>
        <li>Businesses (physical or online)</li>
        <li>Services (physical or online)</li>
        <li>Volunteer Services</li>
        <li>Tutoring</li>
        <li>...etc.</li>
      </ul>
      <a href={% url 'create_new_activity' %}>
      <h3 class="submit-header">Click here to submit an activity</h3>
      </a>
    </div>

    <div class="button-group">
      <a href={% url 'register' %}>
      <button class="button"  style="vertical-align:middle" onclick="document.location=''">
      <span>Register</span>
      </button>
      </a>
      
      <a href={% url 'login' %}>
      <button class="button" style="vertical-align:middle" onclick="document.location=''">
      <span>Login</span>
      </button>
      </a>
      <a href={% url 'logout' %}>
      <button class="button" style="vertical-align:middle; background-color: #DF5252" onclick="document.location=''">
      <span>Logout</span>
      </button>
      </a>

      <div w3-include-html="nav.html"></div>
      
      <script src="script.js"></script>
      <script>includeHTML();</script>
    </div>
    
  </body>
</html>
{% endblock %}

blog/templates/test.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>repl.it</title>
	<link href="style.css" rel="stylesheet" type="text/css" />
</head>

<body>

  <header class='landing'>
	<h1 class="main-header">Meme </h1>
	<form method="POST" class="landing-form" action="index.html">
    {{ form }}
      <button class='submit-btn' type="submit" value='Confirm' />
    </form>
  </header>

    <script src="script.js"></script>
  </body>
</html>

<!--
  <header class="landing">
	<h1 class="main-header">Meme </h1>
	<form method="POST" class="landing-form" action="index.html">
    <label for="id_state">State:</label><select name="state" id="id_state">
  <option value="JOHOR">Johor</option>

  <option value="KEDAH">Kedah</option>

  <option value="KELANTAN">Kelantan</option>

  <option value="MALACCA">Malacca</option>

  <option value="NEGERI SEMBILAN">Negeri Sembilan</option>

  <option value="PAHANG">Pahang</option>

  <option value="PENANG">Penang</option>

  <option value="PERAK">Perak</option>

  <option value="PERLIS">Perlis</option>

  <option value="SABAH">Sabah</option>

  <option value="SARAWAK">Sarawak</option>

  <option value="SELANGOR">Selangor</option>

  <option value="TERENGGANU">Terengganu</option>

  <option value="KUALA LUMPUR">Kuala Lumpur</option>

  <option value="LABUAN">Labuan</option>

  <option value="PUTRAJAYA">Putrajaya</option>

</select>
<label for="id_fully_vaccinated">Fully vaccinated:</label><input type="checkbox" name="fully_vaccinated" id="id_fully_vaccinated">
      <button class="submit-btn" type="submit" value="Confirm">
    
  </button></form></header>